package com.zabuza.vente.ws.entities.test;

import static com.nordnet.common.valueObject.utils.JSon.canBeJSonSerialized;
import static com.nordnet.common.valueObject.utils.Utils.hasProtectedEmptyConstructorEqualsAndHashCodeAndCompareTo;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

import com.nordnet.common.valueObject.identifier.Identifier;
import com.zabuza.vente.ws.entities.Reference;

/**
 * generic test for {@link Reference} entity.
 *
 * this class is auto generated by the com.nordnet.common project : entities-maven-plugin,
 * do not edit this class directly, all change will be lost on next build ...
 */
@SuppressWarnings("unused")
public class ReferenceTest extends GlobalTestCase {

	/**
	 * test  for Reference  methods.
	 * <li> constructors,
	 * <li> {@link Reference#equals(Object)},
	 * <li> {@link Reference#hashCode()},
	 * <li> {@link Reference#toString()}
	 * <li> {@link Reference#compareTo(Reference)}
	 */
	@Test
	public void successTest() {
		Reference tmp = Reference.builder()
			.id(Identifier.build("identifier")).build();
		assertTrue(hasProtectedEmptyConstructorEqualsAndHashCodeAndCompareTo(Reference.class, tmp));
		assertTrue(canBeJSonSerialized(tmp));
	}
}
