package com.zabuza.vente.ws.entities.test;

import static com.nordnet.common.valueObject.utils.JSon.canBeJSonSerialized;
import static com.nordnet.common.valueObject.utils.Utils.hasProtectedEmptyConstructorEqualsAndHashCodeAndCompareTo;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

import com.zabuza.vente.ws.entities.Shop;

/**
 * generic test for {@link Shop} entity.
 *
 * this class is auto generated by the com.nordnet.common project : entities-maven-plugin,
 * do not edit this class directly, all change will be lost on next build ...
 */
@SuppressWarnings("unused")
public class ShopTest extends GlobalTestCase {

	/**
	 * test  for Shop  methods.
	 * <li> constructors,
	 * <li> {@link Shop#equals(Object)},
	 * <li> {@link Shop#hashCode()},
	 * <li> {@link Shop#toString()}
	 * <li> {@link Shop#compareTo(Shop)}
	 */
	@Test
	public void successTest() {
		Shop tmp = Shop.builder()
			.id(null)
			.name("String")
			.description("String").build();
		assertTrue(hasProtectedEmptyConstructorEqualsAndHashCodeAndCompareTo(Shop.class, tmp));
		assertTrue(canBeJSonSerialized(tmp));
	}
}
