package com.zabuza.vente.ws.entities.test;

import static com.nordnet.common.valueObject.utils.JSon.canBeJSonSerialized;
import static com.nordnet.common.valueObject.utils.Utils.hasProtectedEmptyConstructorEqualsAndHashCodeAndCompareTo;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

import org.joda.time.LocalDateTime;
import com.zabuza.vente.ws.entities.User;

/**
 * generic test for {@link User} entity.
 *
 * this class is auto generated by the com.nordnet.common project : entities-maven-plugin,
 * do not edit this class directly, all change will be lost on next build ...
 */
@SuppressWarnings("unused")
public class UserTest extends GlobalTestCase {

	/**
	 * test  for User  methods.
	 * <li> constructors,
	 * <li> {@link User#equals(Object)},
	 * <li> {@link User#hashCode()},
	 * <li> {@link User#toString()}
	 * <li> {@link User#compareTo(User)}
	 */
	@Test
	public void successTest() {
		User tmp = User.builder()
			.id(null)
			.username("String")
			.password("String")
			.name("String")
			.email("String")
			.tel("String")
			.address("String")
			.createDate(LocalDateTime.now())
			.updateDate(LocalDateTime.now())
			.shop(null).build();
		assertTrue(hasProtectedEmptyConstructorEqualsAndHashCodeAndCompareTo(User.class, tmp));
		assertTrue(canBeJSonSerialized(tmp));
	}
}
